name: Build Project-Raptor

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "22.x.x"
            - run: sudo apt update
            - run: sudo apt upgrade -y
            - run: pnpm i -g pnpm
            - run: npm install -g npm
            - run: npm install -g npm
            
